package cli

import (
	"flag"
	"fmt"
	"sort"
	"strings"
)

// This file turns the command table in spec.go into shell completion
// scripts. There is no CLI framework to generate them (ADR-0013), and a
// hand-written script is a second description of the CLI that silently
// stops matching the first — so the scripts are generated from the very
// registrations the parser uses (ADR-0030). A renamed flag changes the
// completion in the same commit, or the spec test fails.

// compFlag is one flag as completion sees it: how it is spelled, what the
// parser says it does, whether it takes a value, and what completes after
// it when it does.
type compFlag struct {
	long    string
	short   string
	help    string
	boolean bool
	cand    candidates
}

// names lists every spelling of the flag, long first.
func (f compFlag) names() []string {
	if f.short == "" {
		return []string{"--" + f.long}
	}
	return []string{"--" + f.long, "-" + f.short}
}

// compCommand is one command as completion sees it.
type compCommand struct {
	name    string
	initial string
	summary string
	flags   []compFlag
	args    candidates
}

// words lists every flag spelling the command accepts, plus the help flag
// the parser answers to without registering.
func (c compCommand) words() []string {
	out := []string{}
	for _, f := range c.flags {
		out = append(out, f.names()...)
	}
	return append(out, "--help", "-h")
}

// isBool reports whether a registered flag is a switch. It is the same
// question the flag package asks itself when deciding whether `--flag`
// consumes the next argument, asked through the same interface.
func isBool(f *flag.Flag) bool {
	b, ok := f.Value.(interface{ IsBoolFlag() bool })
	return ok && b.IsBoolFlag()
}

// completionModel walks the command table, registering each command's
// flags into a throwaway FlagSet so that what is completed is what is
// parsed. Iterating the FlagSet rather than the spec is deliberate: a flag
// the parser accepts is offered even if the spec has not caught up, and
// the spec test is what stops the two from drifting.
func completionModel() []compCommand {
	var out []compCommand
	for _, c := range commandTable() {
		fs := newFlagSet(c.name)
		if c.register != nil {
			c.register(fs)
		}
		shorts, specs := map[string]bool{}, map[string]flagSpec{}
		for _, s := range c.flags {
			specs[s.long] = s
			if s.short != "" {
				shorts[s.short] = true
			}
		}
		cc := compCommand{name: c.name, initial: c.initial, summary: c.summary, args: c.args}
		fs.VisitAll(func(f *flag.Flag) {
			// A one-letter alias is the same flag under a second name
			// (ADR-0021); it is carried by its long form, not listed twice.
			if shorts[f.Name] {
				return
			}
			s := specs[f.Name]
			cc.flags = append(cc.flags, compFlag{
				long: f.Name, short: s.short, help: f.Usage,
				boolean: isBool(f), cand: s.cand,
			})
		})
		out = append(out, cc)
	}
	return out
}

// valueGroup is the set of flag spellings that complete to the same thing,
// across every command. Grouping globally is what keeps the generated
// scripts short: --profile means a profile name wherever it appears.
type valueGroup struct {
	cand  candidates
	names []string
}

// valueGroups collects the flags that take a value: first those with
// something to offer, grouped by what they offer, then one final group of
// the flags whose value no shell can guess. Completion still stops on
// those, because offering flag names where a value belongs is worse than
// offering nothing.
func valueGroups(model []compCommand) (groups []valueGroup, opaque []string) {
	byKey := map[string]*valueGroup{}
	var order []string
	seen := map[string]bool{}
	var opaqueSeen []string
	for _, c := range model {
		for _, f := range c.flags {
			if f.boolean {
				continue
			}
			if f.cand.empty() {
				for _, n := range f.names() {
					if !seen[n] {
						seen[n] = true
						opaqueSeen = append(opaqueSeen, n)
					}
				}
				continue
			}
			key := f.cand.dyn + "\x00" + strings.Join(f.cand.words, " ")
			g, ok := byKey[key]
			if !ok {
				g = &valueGroup{cand: f.cand}
				byKey[key] = g
				order = append(order, key)
			}
			for _, n := range f.names() {
				if !seen[n] {
					seen[n] = true
					g.names = append(g.names, n)
				}
			}
		}
	}
	for _, key := range order {
		groups = append(groups, *byKey[key])
	}
	sort.Strings(opaqueSeen)
	return groups, opaqueSeen
}

// commandWords lists every command spelling: the name and its initial.
func commandWords(model []compCommand) []string {
	var out []string
	for _, c := range model {
		out = append(out, c.name, c.initial)
	}
	return out
}

const generatedBanner = "# Generated by 'screenz update --completions' from the screenz command\n" +
	"# table. Do not edit: regenerate after upgrading screenz.\n"

// CompletionScript renders the completion script for one shell. The shell
// is already known to be supported — install.ResolveShells decides that —
// so the zsh dialect is the last arm rather than an error path.
func CompletionScript(shell string) string {
	model := completionModel()
	switch shell {
	case "bash":
		return bashScript(model)
	case "fish":
		return fishScript(model)
	}
	return zshScript(model)
}

func zshScript(model []compCommand) string {
	var b strings.Builder
	b.WriteString("#compdef screenz sz\n")
	b.WriteString(generatedBanner)
	b.WriteString("\n_screenz() {\n  local -a cmds opts\n  cmds=(\n")
	for _, c := range model {
		fmt.Fprintf(&b, "    '%s:%s'\n", c.name, c.summary)
	}
	b.WriteString("  )\n  if (( CURRENT == 2 )); then\n    _describe -t commands 'screenz command' cmds\n    return\n  fi\n")
	b.WriteString("\n  case ${words[CURRENT-1]} in\n")
	groups, opaque := valueGroups(model)
	for _, g := range groups {
		fmt.Fprintf(&b, "    %s)\n      %s\n      return ;;\n",
			strings.Join(g.names, "|"), zshAdd(g.cand))
	}
	if len(opaque) > 0 {
		fmt.Fprintf(&b, "    %s) return ;;\n", strings.Join(opaque, "|"))
	}
	b.WriteString("  esac\n\n  case ${words[2]} in\n")
	for _, c := range model {
		fmt.Fprintf(&b, "    %s|%s) opts=(%s) ;;\n", c.name, c.initial, strings.Join(c.words(), " "))
	}
	b.WriteString("  esac\n  compadd -- $opts\n")
	b.WriteString("\n  if (( CURRENT == 3 )); then\n    case ${words[2]} in\n")
	for _, c := range model {
		if c.args.empty() {
			continue
		}
		fmt.Fprintf(&b, "      %s|%s) %s ;;\n", c.name, c.initial, zshAdd(c.args))
	}
	b.WriteString("    esac\n  fi\n}\n\n_screenz \"$@\"\n")
	return b.String()
}

// zshAdd renders one candidate set as a compadd call. A dynamic set is
// split on newlines, since a profile name may contain a space.
func zshAdd(c candidates) string {
	if c.dyn != "" {
		return fmt.Sprintf(`compadd -- ${(f)"$(%s)"}`, c.dyn)
	}
	return "compadd -- " + strings.Join(c.words, " ")
}

func bashScript(model []compCommand) string {
	var b strings.Builder
	b.WriteString(generatedBanner)
	b.WriteString("\n_screenz() {\n")
	b.WriteString(`  local cur prev cmd
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  cmd="${COMP_WORDS[1]}"
`)
	b.WriteString("\n  case \"$prev\" in\n")
	groups, opaque := valueGroups(model)
	for _, g := range groups {
		fmt.Fprintf(&b, "    %s)\n      %s\n      return ;;\n",
			strings.Join(g.names, "|"), bashReply(g.cand))
	}
	if len(opaque) > 0 {
		fmt.Fprintf(&b, "    %s) return ;;\n", strings.Join(opaque, "|"))
	}
	b.WriteString("  esac\n\n")
	fmt.Fprintf(&b, "  if [ \"$COMP_CWORD\" -eq 1 ]; then\n    COMPREPLY=( $(compgen -W \"%s\" -- \"$cur\") )\n    return\n  fi\n",
		strings.Join(commandWords(model), " "))
	b.WriteString("\n  if [ \"$COMP_CWORD\" -eq 2 ]; then\n    case \"$cmd\" in\n")
	for _, c := range model {
		if c.args.empty() {
			continue
		}
		fmt.Fprintf(&b, "      %s|%s)\n        %s\n        return ;;\n", c.name, c.initial, bashReply(c.args))
	}
	b.WriteString("    esac\n  fi\n\n  case \"$cmd\" in\n")
	for _, c := range model {
		fmt.Fprintf(&b, "    %s|%s) COMPREPLY=( $(compgen -W \"%s\" -- \"$cur\") ) ;;\n",
			c.name, c.initial, strings.Join(c.words(), " "))
	}
	b.WriteString("  esac\n}\n\ncomplete -F _screenz screenz sz\n")
	return b.String()
}

func bashReply(c candidates) string {
	words := strings.Join(c.words, " ")
	if c.dyn != "" {
		words = "$(" + c.dyn + ")"
	}
	return fmt.Sprintf(`COMPREPLY=( $(compgen -W "%s" -- "$cur") )`, words)
}

func fishScript(model []compCommand) string {
	var b strings.Builder
	b.WriteString(generatedBanner)
	b.WriteString(`
function __screenz_no_command
    set -l t (commandline -opc)
    test (count $t) -eq 1
end

function __screenz_command
    set -l t (commandline -opc)
    test (count $t) -ge 2; and contains -- $t[2] $argv
end

for __screenz_bin in screenz sz
    complete -c $__screenz_bin -f
`)
	for _, c := range model {
		for _, spelling := range []string{c.name, c.initial} {
			fmt.Fprintf(&b, "    complete -c $__screenz_bin -n __screenz_no_command -a %s -d '%s'\n",
				spelling, c.summary)
		}
	}
	for _, c := range model {
		cond := fmt.Sprintf("__screenz_command %s %s", c.name, c.initial)
		if !c.args.empty() {
			fmt.Fprintf(&b, "    complete -c $__screenz_bin -n '%s' -a %s\n", cond, fishWords(c.args))
		}
		for _, f := range c.flags {
			fmt.Fprintf(&b, "    complete -c $__screenz_bin -n '%s' -l %s%s%s -d '%s'\n",
				cond, f.long, fishShort(f), fishValue(f), f.help)
		}
	}
	b.WriteString("end\n")
	return b.String()
}

func fishShort(f compFlag) string {
	if f.short == "" {
		return ""
	}
	return " -s " + f.short
}

// fishValue marks a flag that takes a value as exclusive (-x: a value is
// required and file names are not offered) and attaches its candidates.
func fishValue(f compFlag) string {
	if f.boolean {
		return ""
	}
	if f.cand.empty() {
		return " -x"
	}
	return " -x -a " + fishWords(f.cand)
}

func fishWords(c candidates) string {
	if c.dyn != "" {
		return "'(" + c.dyn + ")'"
	}
	return "'" + strings.Join(c.words, " ") + "'"
}
